services:
  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  blackbox:
    image: prom/blackbox-exporter:v0.27.0
    ports:
      - "9115:9115"

  speedtest:
    image: miguelndecarvalho/speedtest-exporter:v3.5.4
    ports:
      - "9798:9798"

  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboard-7587.json:/etc/grafana/provisioning/dashboards/dashboard-7587.json
      - ./grafana/dashboard-13665.json:/etc/grafana/provisioning/dashboards/dashboard-13665.json

volumes:
  grafana-storage:
  prometheus-storage:


networks:
  default:
    ipam:
      config:
        - subnet: 172.30.0.0/16
